version: "3.8"

services:
  app:
    image: ghcr.io/korjavin/eaterplatform:94b7ffc7c3d5223d84ae031856a0cb9ddc2b8476
    container_name: eaterplatform
    environment:
      - DATABASE_PATH=/app/data/eater.db
    volumes:
      - eater_data:/app/data
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK_NAME:-traefik_default}"
      - "traefik.http.routers.eaterplatform.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.eaterplatform.entrypoints=websecure"
      - "traefik.http.routers.eaterplatform.tls.certresolver=myresolver"
      - "traefik.http.services.eaterplatform.loadbalancer.server.port=8080"
    restart: unless-stopped

volumes:
  eater_data:

networks:
  traefik_network:
    external: true
    name: ${TRAEFIK_NETWORK_NAME:-traefik_default}
